name: Update Submodules

on:
  workflow_dispatch:

jobs:
  update-submodules:
    runs-on: ubuntu-latest
    name: Update Submodules
    steps:
      - name: Checkout main repository only
        uses: actions/checkout@v4
        with:
          submodules: false
          
      - name: Setup Git
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          
      - name: Manual submodule update
        run: |
          # 手动处理每个子模块
          submodules=$(git config --file .gitmodules --get-regexp path | awk '{print $2}')
          for submodule in $submodules; do
            echo "Processing submodule: $submodule"
            if [ -d "$submodule" ]; then
              cd "$submodule"
              git checkout main
              git pull origin main
              cd ..
            else
              git submodule update --init "$submodule"
            fi
          done
          
      - name: Commit and push
        run: |
          if git diff --quiet; then
            echo "No changes"
          else
            git add .
            git commit -m "Update submodules"
            git push
          fi
