name: Update All Submodules

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *' # 每天UTC时间午夜运行

jobs:
  update-submodules:
    runs-on: ubuntu-latest
    name: Update All Submodules
    steps:
      - name: Checkout main repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          submodules: false

      - name: Setup Git
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      - name: Update each submodule individually
        run: |
          # 更新每个子模块到最新的 main 分支
          git submodule update --init --remote --merge "2022秋_2023春_大学物理实验_实验报告"
          git submodule update --init --remote --merge "2023春_高级语言程序设计_2023秋_面向对象程序设计_课程项目"
          git submodule update --init --remote --merge "2023秋_数据结构课程设计_课程项目"
          git submodule update --init --remote --merge "2023秋_数据量化推理_课程项目"
          git submodule update --init --remote --merge "2023秋_离散数学_课程作业"
          git submodule update --init --remote --merge "2023秋_程序设计范式_课程作业"
          # 跳过 "2023秋_程序设计范式_课程项目" 因为有 update = none
          git submodule update --init --remote --merge "2023秋_计算机组成原理实验_实验报告"
          git submodule update --init --remote --merge "2024春_人工智能导论_课程作业"
          git submodule update --init --remote --merge "2024春_大数据与人工智能_课程作业"
          git submodule update --init --remote --merge "2024春_操作系统_课程作业"
          git submodule update --init --remote --merge "2024春_操作系统课程设计_课程项目"
          git submodule update --init --remote --merge "2024春_数据库课程设计_课程项目"
          git submodule update --init --remote --merge "2024春_用户交互技术_课程作业"
          git submodule update --init --remote --merge "2024春_用户交互技术_课程项目"
          git submodule update --init --remote --merge "2024春_算法设计与分析_课程作业"
          git submodule update --init --remote --merge "2024春_计算机系统结构_研究学习"
          git submodule update --init --remote --merge "2024春_计算机网络实验_实验报告"
          git submodule update --init --remote --merge "2024秋_区块链导论_课程作业"
          git submodule update --init --remote --merge "2024秋_区块链导论_课程项目"
          git submodule update --init --remote --merge "2024秋_嵌入式系统导论_课程作业"
          git submodule update --init --remote --merge "2024秋_汇编语言_课程作业"
          git submodule update --init --remote --merge "2024秋_物联网应用基础_课程作业"
          git submodule update --init --remote --merge "2024秋_物联网应用基础_课程项目"
          git submodule update --init --remote --merge "2024秋_移动应用开发_课程作业"
          git submodule update --init --remote --merge "2024秋_移动应用开发_课程项目"
          git submodule update --init --remote --merge "2024秋_计算机视觉_课程作业"
          git submodule update --init --remote --merge "2024秋_计算机视觉_课程项目"
          git submodule update --init --remote --merge "2024秋_语音识别_课程作业"
          git submodule update --init --remote --merge "2024秋_语音识别_课程项目"
          git submodule update --init --remote --merge "2024秋_软件工程_课程作业"
          git submodule update --init --remote --merge "2024秋_软件工程课程设计_课程项目前端"
          git submodule update --init --remote --merge "2024秋_软件工程课程设计_课程项目后端"
          git submodule update --init --remote --merge "2024秋_软件设计模式_课程作业"
          git submodule update --init --remote --merge "2025春_SLAM理论与系统_课程项目"
          git submodule update --init --remote --merge "2025春_专业方向综合项目_课程作业"
          git submodule update --init --remote --merge "2025春_专业方向综合项目_课程项目"
          git submodule update --init --remote --merge "2025春_机器学习_吴恩达机器学习专项课程"
          git submodule update --init --remote --merge "2025春_机器学习_课程作业"
          git submodule update --init --remote --merge "2025春_群体智能_课程作业"
          git submodule update --init --remote --merge "2025春_群体智能_课程项目"
          git submodule update --init --remote --merge "2025春_软件工程管理与经济_课程作业"
          git submodule update --init --remote --merge "2025春_软件测试_课程项目"
          git submodule update --init --remote --merge "LaTeX_同济大学本科毕业设计理工类论文模板"
          git submodule update --init --remote --merge "LaTeX_同济大学演示文稿模板"

      - name: Commit and push changes
        run: |
          # 检查是否有更改
          if git diff --quiet; then
            echo "No changes in submodules"
          else
            git add .
            git commit -m "chore: update all submodules to latest versions"
            git push
          fi
